apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exports
  namespace: fileserver
spec:
  # use default storage class to get autoprovisioning from admission
  #  controller
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
