apiVersion: v1
kind: Service
metadata:
  name: fileserver
  labels:
    name: fileserver
  namespace: fileserver
spec:
  type: NodePort
  selector:
    name: fileserver
  ports:
  - name: nfsd
    protocol: TCP
    port: 2049
    targetPort: 2049
  - name: nfsdudp
    protocol: UDP
    port: 2049
    targetPort: 2049
  - name: portmapper
    protocol: TCP
    port: 111
    targetPort: 111
  - name: portmapperudp
    protocol: UDP
    port: 111
    targetPort: 111
  - name: statd
    protocol: TCP
    port: 32765
    targetPort: 32765
  - name: statdudp
    protocol: UDP
    port: 32765
    targetPort: 32765
  - name: mountd
    protocol: TCP
    port: 32767
    targetPort: 32767
  - name: mountdudp
    protocol: UDP
    port: 32767
    targetPort: 32767
    
